### ISSUE TITLE
Paper's v2 Web API

### ISSUE THREAD

**Issue by Protonull** [CivClassic/AnsibleSetup#124]
> Excuse the interruption, but we have some news:
> 
> Version 2 of the PaperMC downloads API is now live - documentation can be read at https://papermc.io/api/docs/ (you can also try the API out here, too!)
> 
>  WARNING 
> -   Version 1 of the downloads API is now deprecated
> -  Public access to Jenkins will be removed at the end of December 2020 - please move to using our API as soon as possible to avoid any disruptions.
> 
> If you encounter any issues, please report them to us.

This ^ was posted in the PaperMC Discord on the 24th November and signals the deprecation of v1, the api we're currently using to download the latest available build for 1.16.1. This isn't necessarily an imminent problem since it *might* be a long time until they shutdown the v1 api completely, but we're going to have to face this sooner or later.

https://github.com/CivClassic/AnsibleSetup/blob/559492bc0022fcc833f56fbf1aae1321be206fe4/variables/all.yml#L132-L133

This ^ is what we're currently using to download 1.16.1, but there's no equivalent to this with v2 which instead has this pattern: `https://papermc.io/api/v2/projects/{project}/versions/{version}/builds/{build}/downloads/{download}` with the 1.16.1 example being: `https://papermc.io/api/v2/projects/paper/versions/1.16.1/builds/138/downloads/paper-1.16.1-138.jar`

This isn't so much of a problem right now since we're using 1.16.1, a version that isn't being actively developed, so we can just paste the URL above and be done with it, but should we update to the latest version that is actively developed, we may have to be diligent in updating this Ansible setup with the newer versions unless we come up with some other solution.

**Comment by Maxopoly** [comment]
Paper apparently explicitly does not want people to automatically pull latest as they can't guarantee it being bug free, one of their core devs (kashike) said in Discord

> The point is to not provide a direct link to the latest build - we do not encourage people to download the latest build each time they start their server, which many people have done - and this has resulted in worlds becoming corrupt.

So the goal here should be to introduce an additional variable determining the paper version used

**Comment by Maxopoly** [comment]
Implemented by https://github.com/CivClassic/AnsibleSetup/commit/821c30407708a8309713cfa559b5f6ec684f7822

Good issue, thanks for bringing it up.
