### ISSUE TITLE
AnsibleSetup's growing size

### ISSUE THREAD

**Issue by Protonull** [CivClassic/AnsibleSetup#127]
We probably ought to speak about AnsibleSetup's size. It currently sits at 140MB on disk and 88.4MB of that is *just* the git folder, and that's just going to keep growing. While I'm aware that 140MB is not especially large, that webkit apps are larger, and that it's been over a year and a half since the creation of AnsibleSetup so a 140MB size in that time is not too bad, but I don't think we need to wait for it to be 1GB before we even have a discussion about it.

There's likely a number of things we could, of course some things would take more effort than others, but still I think we should move towards reduce the data burden regardless.

**Comment by Maxopoly** [comment]
That's because we are putting binaries (all the live server jars) into a git repo. I suppose we could change the official recommendation to use `--depth 1` when cloning the repo (which excludes history)?

**Comment by Protonull** [comment]
SoundTech taught us about `--depth 1` last night and this seems like the best long term solution.

**Comment by Maxopoly** [comment]
Resolved by https://github.com/CivClassic/AnsibleSetup/commit/921d37660568fc19dc74fc09707c9c18eedde3c3
