### ISSUE TITLE
Upgrading to Java 16 + MC 1.17

### ISSUE THREAD

**Issue by Protonull** [CivClassic/AnsibleSetup#175]
iirc we upgraded to Java 11 as part of the 1.16.1 or 1.16.4 update, which didn't pose many issues. Upgrading to Java 16 will pose a few issues, particularly in regards to reflection, but nothing that cannot be fixed.

**Comment by Protonull** [comment]
https://github.com/CivClassic/AnsibleSetup/pull/194 Should fix some of the problems of updating to Java 16 too

**Comment by Protonull** [comment]
PaperMC has recently updated one of their forum posts:

> From Paper 1.16.5 build 668 forward the server will log a large warning in the console if it detects the server is running on Java 15 or below. We’re hoping this warning and the several months of advanced notice we’re giving will allow people to be updated long before we drop support for Java 8.
>
> [Reference](https://papermc.io/forums/t/java-16-mc-1-17-and-paper/5615)

We're currently using build 581, so we're a little behind, but it's safe to say that we're likely going to want to upgrade to Java 16 *before* we upgrade to Minecraft 1.17. And while I freely admit that a version warning isn't exactly dire, we should probably seek to upgrade anyway due to the general performance improvements and newer features available in newer versions of Java.. who knows, it very well may be the case that some of our lag problems disappear when we upgrade.

For this reason, @wingzero54, would you be able to create a github project page for updating / upgrading each plugin we use to Java 16?

**Comment by Protonull** [comment]
Update progress:

# Bukkit
- [ ] AAC
- [ ] AACPlus
- [ ] BanStick
- [ ] Bastion
- [ ] BetterChairs
- [ ]  Brewery
- [ ] BungeeGuard
- [ ] Citadel
- [ ] CivChat2
- [ ] CivDuties
- [ ] CivModCore
- [ ] ClearLag
- [ ] CombatTagPlus
- [ ] ConditionalCommands
- [ ] CraftEnhance
- [ ] Donum
- [ ] EssenceGlue
- [ ] ExilePearl
- [ ] FactoryMod
- [ ] Finale
- [ ] HiddenOre
- [ ] HolographicDisplays
- [ ] ItemExchange
- [ ] JukeAlert
- [ ] KiraBukkitGateway
- [ ] LuckPerms
- [ ] NameColors
- [ ] NameLayer
- [ ] Orebfuscator
- [ ] ProtocolLib
- [ ] RailSwitch
- [ ] RandomSpawn
- [ ] RealisticBiomes
- [ ] SimpleAdminHacks
- [ ] Spark
- [ ] SuperVanish
- [ ] Vault
- [ ] Votifier #This is actually NuVotifier
- [ ] WDLCompanion
- [ ] WorldBorder
- [ ] WorldEdit
- [ ] TAB

# Bungee
- [ ] BungeeGuard
- [ ] Spark
- [ ] ViaBackwards
- [ ] ViaVersion

**Comment by Protonull** [comment]
https://github.com/CivClassic/SimpleAdminHacks/pull/76 fixes SimpleAdminHacks' compilation issues, however it shouldn't be merged yet given that https://github.com/CivClassic/SimpleAdminHacks/pull/72 adds new tests that'll have to be updated for Java 16 too.

**Comment by Protonull** [comment]
https://github.com/CivClassic/Brewery/pull/8 fixes its compilation issues

**Comment by Diet-Cola** [comment]
RB compiling fine on my local 16/17 branch for 1.17 & java 16

**Comment by Diet-Cola** [comment]
NL compiling on my local 16+17 branch for 1.17 & java 16

**Comment by Protonull** [comment]
Civclassic Parent PR: https://github.com/CivClassic/style-guide/pull/13
CivModCore PR: https://github.com/CivClassic/CivModCore/pull/104
BanStick PR: https://github.com/CivClassic/BanStick/pull/29

**Comment by Protonull** [comment]
Just to mention, given how certain things are getting harder with standard Java tools, like NameLayer setting civ-names via reflection, we should seriously consider having our own server fork. I've been toying with one here: https://github.com/Protonull/DeepState and with the new tools from PaperMC it's like stupidly easy to maintain. It'll also allow us to control the which version we use more precisely, as well as take advantage of Tuinity additions.

**Comment by Diet-Cola** [comment]
Citadel v4.2.0 - Compiles locally on my branch

**Comment by Diet-Cola** [comment]
HiddenOre v1.8.0 - local branch

**Comment by Diet-Cola** [comment]
Bastion v2.5.0 - local branch

**Comment by Diet-Cola** [comment]
Brewery v3.1 - https://github.com/DieReicheErethons/Brewery

**Comment by Diet-Cola** [comment]
Brewery - on my local branch, updated w/ compat for citadel/NL

**Comment by Diet-Cola** [comment]
Civchat2 1.9.0 - local branch

**Comment by Diet-Cola** [comment]
FM v2.6.0 - local branch

**Comment by Diet-Cola** [comment]
NameColours v1.2.0 - local branch

**Comment by Diet-Cola** [comment]
RailSwitch v1.6.0 - local branch

**Comment by Diet-Cola** [comment]
Finale v1.6.0 - local branch
