### ISSUE TITLE
Update ViaVersion and ViaBackwards

### ISSUE THREAD

**Issue by Protonull** [CivClassic/AnsibleSetup#208]
About two hours ago, Via\* announced a new version of their Via\* plugins: 4.0.0

I've just asked and while they support Java 16 and Minecraft 1.17, we can still use them on our current Java 11 and Minecraft 1.16.5 to allow for Minecraft 1.17 clients to connect. The downloads are:

* [ViaVersion](https://github.com/ViaVersion/ViaVersion/releases/tag/4.0.0)
* [ViaBackwards](https://github.com/ViaVersion/ViaBackwards/releases/tag/4.0.0)

**Comment by Diet-Cola** [comment]
On test

**Comment by Protonull** [comment]
Everything seems to work fine
