### ISSUE TITLE
RandomSpawn - spawns should be randomized

### ISSUE THREAD

**Issue by wingzero54** [CivClassic/AnsibleSetup#221]
Currently it attempts spawns from the start of the list down. It needs to pick random entries from the list and attempt to spawn, then move to another random entry

**Comment by Gjum** [comment]
picking randomly and moving on might not terminate (see devoted 3.0); instead sort the list randomly (it's short), try in order, and if none were acceptable, do the default action (world spawn point? completely random?).

**Comment by wingzero54** [comment]
Yeah that seems fine. I think the random spawn is 7000 blocks around 0,0

**Comment by wingzero54** [comment]
So this was a pretty big misunderstanding. RandomSpawn does pick randomly from the list, the issue is we made erroneous assumptions in the city spawn config and because of that, only one or two cities ended up actually eligible for spawning. It is fixed now and acting as intended
