### ISSUE TITLE
Diamond spawn rates were changed

### ISSUE THREAD

**Issue by Maxopoly** [CivClassic/AnsibleSetup#28]
Seemingly returning to HiddenOre main line and thus switching over to Devoteds vein algorithm has modified diamond rates. Need to investigate what exactly changed and how to adjust the config to resemble previous behavior.

**Comment by KaloHG** [comment]
I have access to a similar config to the CivClassic's one. I'll put together a proper config YML with the new namespaced ID's.

**Comment by Maxopoly** [comment]
I don't think this issue is related to namespaced ids, all of those parse fine. Current config is here https://github.com/CivClassic/AnsibleSetup/blob/master/templates/public/plugins/HiddenOre/config.yml.j2

**Comment by KaloHG** [comment]
HARD_CLAY should be changed to TERRACOTTA/LEGACY_HARDENED_CLAY, it was deprecated/removed in the 1.13 update.

**Comment by KaloHG** [comment]
A few of the tools, for example GOLD_PICKAXE, etc are broken. I wonder if something in the actual plugin generator was changed. However, it does not look like it. I'll run a few more tests to see if there is a seperate issue.

**Comment by Maxopoly** [comment]
Ok cool, [here](https://pastebin.com/wqK0UYqa) is the 1.12 config used before (seed changed ofc)

**Comment by KaloHG** [comment]
Alright, Done! Here is an image of the vein generation on a default world. https://i.imgur.com/r0kHzP3.png. Ignore the ores in the background, thats merely vanilla generation. I highlighted the ores that are new. Attached is the new configuration file. I'd reccomend looking over it to make sure I did not mess something up. Anyways, thanks for the help. (Just change the txt to yml.)
[config.txt](https://github.com/CivClassic/AnsibleSetup/files/4658852/config.txt)

**Comment by KaloHG** [comment]
(I'll put a commit request to the repo template now.)

**Comment by Maxopoly** [comment]
I already did here https://github.com/CivClassic/AnsibleSetup/pull/31/files

**Comment by KaloHG** [comment]
Alrighty, Thanks.

**Comment by Diet-Cola** [comment]
On personal testing: 
There seems to be some sort of linking between diamond_ore_transform & diamond_ore_vein, [using the devoted vein config example](https://github.com/DevotedMC/HiddenOre/blob/master/src/main/resources/config-veins.yml) we know veins work, its just something to do with config.

**Comment by Maxopoly** [comment]
Initial reports indicate that https://github.com/CivClassic/AnsibleSetup/commit/b12d7ba4439d285d2e31b8efadbc7e0b713943a1 succeeded in fixing it, so closing this for now.
