### ISSUE TITLE
Migrate to Python3

### ISSUE THREAD

**Issue by Maxopoly** [CivClassic/AnsibleSetup#43]
Also update installer readme etc.

Long overdue, 2.7 is deprecated

**Comment by Protonull** [comment]
The biggest issue is probably going to be the database connection stuff

**Comment by Maxopoly** [comment]
Should be addressed as part of https://github.com/CivClassic/AnsibleSetup/commit/03382f6e1c18ed85e963347f6092f1c30f9217a5 ,only a documentation change due to Ansibles modular nature.
