### ISSUE TITLE
Update to ViaVersion 3.0.1

### ISSUE THREAD

**Issue by Protonull** [CivClassic/AnsibleSetup#44]
This will allow people to connect with 1.16 clients

**Comment by Maxopoly** [comment]
https://github.com/CivClassic/AnsibleSetup/commit/54a71ffbb91bebe616964b74a154dedc373379ce

**Comment by Protonull** [comment]
Still seems to be `2.2.3`

**Comment by Maxopoly** [comment]
Yes, because of https://github.com/CivClassic/AnsibleSetup/issues/16

**Comment by Maxopoly** [comment]
I had also not renamed the target jar, which I fixed in https://github.com/CivClassic/AnsibleSetup/commit/8dc301648ec7fb5ffed8103679c41147255f3147

**Comment by Protonull** [comment]
Fair
