### ISSUE TITLE
obfuscate to a non-stone block depending on surrounding blocks

### ISSUE THREAD

**Issue by Gjum** [CivClassic/AnsibleSetup#51]
this was brought up by max in #50:

> per biome overrides for the nether? With this setup any snitches etc. would still stick out in all the netherrack

the same goes for building blocks (obsidian) and different y levels (sand, dirt, ...), so it's not really biome specific, but rather dependent on surrounding blocks.

possible methods I brought up in the past were:

- pick the most common block type out of the surrounding 6 face-adjacent blocks (or 5 (4) if at a chunk border (corner))
- always pick the block type north of the obfuscated block (north is arbitrary here; and in case of chunk boundary, pick any other block face in precedence order)

in case the adjacent blocks are also obfuscated blocks, treat them as out-of-world like above, or fall back to stone, etc.

does orebfuscator have an option for this? if not it might be worth it moving this issue to its repo.

what's the performance hit? if it's non-negligible, is it worth it vs. just always obfuscating to stone/biome-default?

**Comment by Nuclear-Crow** [comment]
If you still want to fall back to default when something like [this](https://prnt.sc/tib2h2) comes up, why bother with adaptiveness in the first place

**Comment by Gjum** [comment]
in your screenshot, each obfuscated block still has an adjacent stone block, so with both methods they would all be obfuscated correctly; maybe my explanation was unclear. in any case, this is a heuristic, so breaking in extreme cases (e.g., 3x3 cube of noteblocks) isn't a problem with respect to the overall improvement.

do you know other edge cases? or other methods of block type selection that catch more cases or are easier on performance?

**Comment by Maxopoly** [comment]
Implemented by https://github.com/CivClassic/AnsibleSetup/pull/123
