### ISSUE TITLE
Orebfuscator does not use intended config

### ISSUE THREAD

**Issue by Falvyu** [CivClassic/AnsibleSetup#62]
As the title suggests, Orebfuscator does not the load configs at `plugins/Orebfuscator/` but rather `plugins/Orebfuscator4/`. It seems to be related to the fact that the plugin's name is `Orebfuscator4` ( https://github.com/lishid/Orebfuscator/blob/v4.3.0-release-2/Plugin/pom.xml#L10 ) instead of simply `Orebfuscator`.

With the current Ansible scripts, the intended configurations are placed at `plugins/Orebfuscator/` and therefore won't be loaded.

**Comment by Maxopoly** [comment]
Ah, nice catch. Fixed in https://github.com/CivClassic/AnsibleSetup/commit/f44495decc4f2b8b8d1b752b55f0901022492389
