### ISSUE TITLE
Corrupted Chunks

### ISSUE THREAD

**Issue by Protonull** [CivClassic/AnsibleSetup#69]
While the server was on 1.14, it seemed like some of the chunks were bugging out, as if Orebfuscator was applying the anti-xray mechanic above ground. Since the 1.16 update (and using 1.16 clients) those chunks have bugged out in a different way, where certain blocks *appear* as certain blocks until they're updated (either by right click or redstone etc) into their original blocks.

**Comment by Protonull** [comment]
Video: https://youtu.be/QHR5rjdidR4

**Comment by Maxopoly** [comment]
Possibly related to https://github.com/CivClassic/AnsibleSetup/issues/68

**Comment by Maxopoly** [comment]
I will delete the orebufscator cache later and see if that maybe fixes it

**Comment by Maxopoly** [comment]
Seemingly fixed by deleting the cache
