### ISSUE TITLE
Ghast and Pigmen spawned by SAH dont despawn

### ISSUE THREAD

**Issue by Maxopoly** [CivClassic/AnsibleSetup#91]
They just keep piling up, eventually causing lagg. Need to adjust the clearlag config accordingly

**Comment by wingzero54** [comment]
Resolved with [this commit](https://github.com/CivClassic/AnsibleSetup/commit/bceb1266022492db4d7e675004f73688c65affcc#diff-46340852cdad78cae5a502c0f772327c7d7ab7d2132fa52030297585776d0f45) which has ghasts and pigmen cull at chunk limits to prevent piling up
