### ISSUE TITLE
Ghast spawning from portals is too high

### ISSUE THREAD

**Issue by Maxopoly** [CivClassic/AnsibleSetup#92]
Lower in SAH  config

**Comment by wingzero54** [comment]
Ghast spawns were reduced quite a bit by [this commit](https://github.com/CivClassic/AnsibleSetup/commit/5cd404166d28662173d3bd22ce8969d651fbac93#diff-fea615bd8d572ea062b828b5ff88cacc8d76c347f6dce4153572ab6b1616610f)
